### ISSUE TITLE
Hello, is it possible run sql query in Bean or python script?

### ISSUE THREAD

**Issue by muyufan** [openjump-gis/openjump#102]
I couldn't find such example build-in bean/python examples.

**Comment by mukoki** [comment]
Here is a beanshell script with some functions which can help you (you'll have to remove .txt extension).
You'll need two more lines to define your connection and your query, e.g
```
conn = connect("jdbc:postgresql://localhost:5432/yourbasename", "user", "password");
loadInLayer("category name", "layer name", conn, "SELECT * from matable");

```
You can edit it and test it from beanshell Editor, remove unused functions, wrap your code in a Thread if you want it to be non blocking, etc.
[query_db.bsh.txt](https://github.com/openjump-gis/openjump/files/11642521/query_db.bsh.txt)

**Comment by muyufan** [comment]
@mukoki Thanks a lot, it works.
