### ISSUE TITLE
Reading jpeg 2000

### ISSUE THREAD

**Issue by mukoki** [openjump-gis/openjump#106]
At the moment I currently use two well-known image formats which gradually lead me to use qgis rather than OpenJUMP : jp2 and COG.
OpenJUMP has several jp2 drivers, but I could never read jp2 images correctly with them (I generally get a very low resolution image if any).
I just included a new java driver based on OpenJPEG : https://github.com/dbmdz/imageio-jnr
It is OK for my use, but It still misses native libraries for linuw/osx. Should not be difficult to add though.
It has another major drawback : it can't read jp2 georeferencing tags. For now on, I managed georeferencement from .j2w or .tab, but I hope that at some point, imageio-jnr will make it possible to get jp2 geo-metadata.
@edeso , maybe you would like to have a look at it and include other native libs

About COG, it is basically a GeoTiff file following some conventions to wrap a pyramid of images making it efficient at different scales.

**Comment by jratike80** [comment]
There is a PR that has been open for 6 years soon https://github.com/uclouvain/openjpeg/issues/1109. I do not understand how GDAL can write and read those associated boxes for GeoJP2 and GMLJP2.

When it comes to COG, I think that the idea behind using COG in an efficient way is that the client does not  read the whole image but only the area or the map window, and at a reasonable resolution. I believe that OpenJUMP currently needs to read the whole TIFF image. However, the ECW driver and WMS driver work in that way and they request new data after each pan/zoom so we have some code for such usage.

As a workaround I have sometimes been running Mapserver or Geoserver in localhost for serving WMS layers to OpenJUMP. You could try the same with QGIS Server.

**Comment by edeso** [comment]
Mike, Jukka,

1. did you ever install the GDAL-libs and tried the ImageIO-Ext OpenJPEG driver? that should be the most versatile. 
2. do you have test images?
3. how are JP2 files supposed to keep there referencing. is there some standard aside from sidecar files?

**Comment by mukoki** [comment]
1. forgot that there is some lib to install for gdal. Just tried to follow instruction found in https://ojwiki.soldin.de/index.php?title=Working_with_Raster but did not suceed (generally, I get the message "Can't register JP2GDAL readers.")
2. you can download orthophotographies of France here : https://geoservices.ign.fr/telechargement-api/BDORTHO?zone=D075 (I selected Paris as it should be smaller than other regions, also old ones are smaller (0.5m resolution) than new ones (0.15)
3. As mentioned by Jukka, there are two ways to represent georeferencing in jp2 metadata, but I don't know more about it (seems to me that it is more common to use internal metadata than sidecar files for jp2).

**Comment by jratike80** [comment]
3a. The GMLJP2 standard is https://docs.ogc.org/is/08-085r4/08-085r4.html but I think that it is not realistic that OpenJUMP would do the low level access to the JPEG2000 code stream and boxes. But if the JPEG2000 library can do that and return the raw GML from the box it is not so hard to read the coordinate system, origin, and pixel size.

3b. The GeoJP2 system is older and the copyright belongs now to the company Extensis. They have removed the specification from the web but the idea and a Timemachine link are expressed in https://github.com/opengeospatial/geotiff/issues/97#issuecomment-929196283. The idea is simply to insert a 1x1 pixel sized GeoTIFF image with all the geotiff tags that are needed inside JPEG2000 into a box. Here again it may be unrealistic to make OpenJUMP to extract the box, but when the GeoTIFF is out than any GeoTIFF driver has the capabilities to read the georeferencing.

I wonder if someone has already written an utility that can read JPEG2000 and extract the georeferencing into an external file, for example in the .aux.xml format that GDAL is using. Such utility would not need to understand everything about JPEG200, just how to export the contents of certain boxes.

**Comment by edeso** [comment]
just for fun also tried recent `jdk-21.0.2+13.x64-adoptium` and quickly assembled https://sourceforge.net/projects/jump-pilot/files/OpenJUMP_plugins/Drivers/GDAL-win-x86x64-3.8.4stable-20240311.zip .

loads as well, albeit it seems twice slower for some reason.

can anyone of you confirm that it works in general?

**Comment by edeso** [comment]
just noticed that you (Mike) added 
```
A lib/native/x64/openjp2.dll
```
this'll probably clash with the `openjp2.dll` provided by GDAL.might explain your **Can't register JP2GDAL readers.**

**Comment by mukoki** [comment]
Hi Ede,
I could finally install gdal. Just had to copy gdal-win-x64 "beside" x64 folder, not "inside".
Works pretty well. First load is a bit slow (10 s on my machine while the new plugin displays the same image in less than a second), but after that, navigation with gdal is a bit faster than with the new plugin.
Good to know.
Installing a 150M dependency (twice the size of OpenJUMP), is probably not optimal, but I know there is a lot of stuff coming with gdal. Also I will test it with some other interesting formats like bigtiff and COG now that I know how to install it ;-)
Jukka has also good hints to read jp2 metadata. If I can find a way to do it, having a jp2 driver which is less than 1M and does not need additional installation is good.
I don't know if the added openjp2.dll and the gdal one may clash but If gdal is properly installed, I can drop the dll I added. Not sure I want to replace a 350k dll by a 150M dependency though.
Thank you for the help

**Comment by edeso** [comment]
> I could finally install gdal. Just had to copy gdal-win-x64 "beside" x64 folder, not "inside".

that's explained in the accompanying INSTALL-xxx.txt inside the Zip-File. any suggestion to improve documentation i'm all ears.

> I don't know if the added openjp2.dll and the gdal one may clash but If gdal is properly installed, I can drop the dll I added. Not sure I want to replace a 350k dll by a 150M dependency though.

we may be able to strip out the files needed for GDAL support. just never took the time to do so. maybe one of you want's to tackle that ;)

**Comment by mukoki** [comment]
new JP2 driver added on march, between 10 and 30
