### ISSUE TITLE
Image reading interpolation

### ISSUE THREAD

**Issue by mukoki** [openjump-gis/openjump#108]
Some image readers read image without any interpolation (seems to be the case with ImageIO-Ext).
Others use a bicubic interpolation (like subclasses of AbstractGraphicImages used by Commons Imaging).
Nothing wrong but not very consistant.
A solution would be to add a general option in the option panel, or a per layer "style".
In the meantime, my preference is to have no interpolation because for technical work, I like to see pixels squares. Any one against it ?

**Comment by edeso** [comment]
sounds reasonable.

**Comment by mukoki** [comment]
Interpolation removed with AbstractGraphicImages and Commons Imaging (no option implemented for now)
