### ISSUE TITLE
Regression in RasterTools extension after commons-imaging upgrade

### ISSUE THREAD

**Issue by mukoki** [openjump-gis/openjump#109]
This one is for you Peppe,

I've recently upgraded commons-imaging to 1.0.0-alpha4 in OpenJUMP. The main benefit is it can now read bigtiff.
Unfortunately, there are small api changes in this version. The breaking one for RasterTools is that ImageReadException has been replaced by ImagingException.
There are also changes with bytesource package, but I'm not sure you need it.
Let me know if you can upgrade RasterTools for that. If you need time, I can deactivate the extension until we get a new version.

**Comment by ma15569** [comment]
Thanks Michael
I will give a look in the next days.


Il ven 12 apr 2024, 18:57 Michaël Michaud ***@***.***> ha
scritto:

**Comment by ma15569** [comment]
Hi Michaël, 
I upgraded RasterTool plugin in order to work with  commons-imaging 1.0.0-alpha4. 
I sent a pull request.

**Comment by edeso** [comment]
asrequested
