### ISSUE TITLE
Crs position in geojson

### ISSUE THREAD

**Issue by mukoki** [openjump-gis/openjump#40]
I've been told that crs defined at the feature level are not recognized by other libraries (notably python reference libraries).
As I understand
https://gist.github.com/sgillies/1233327
A crs defined at the feature or the geometry level is right but when all features have the same crs, it should be defined at the FeatureCollection level :

"The crs member should be on the top-level GeoJSON object in a hierarchy (in
  feature collection, feature, geometry order) and should not be repeated or
  overridden on children or grandchildren of the object. "

**Comment by jratike80** [comment]
The crs in GeoJSON is sort of orphaned because https://datatracker.ietf.org/doc/html/rfc7946 let's it all to a agreement between data provider and user.

However, I would say that defining crs only one time and at the highest possible level feels right, and the whole feature collection should use just single crs. Users who need something exotic should use GML for that.

**Comment by mukoki** [comment]
Thanks for the comment Jukka,Michaëlenvoyé : 18 septembre 2021 à 22:49de : Jukka Rahkonen ***@***.***>à : openjump-gis/openjump ***@***.***>cc : Michaël Michaud ***@***.***>, Author ***@***.***>objet : Re: [openjump-gis/openjump] Crs position in geojson (#40) The crs in GeoJSON is sort of orphaned because https://datatracker.ietf.org/doc/html/rfc7946 let's it all to a agreement between data provider and user.However, I would say that defining crs only one time and at the highest possible level feels right, and the whole feature collection should use just single crs. Users who need something exotic should use GML for that.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
