### ISSUE TITLE
QuasiMode broken

### ISSUE THREAD

**Issue by jratike80** [openjump-gis/openjump#44]
Keyboard shortcuts (Alt, Ctrl, Shift-Alt etc) do not work. Perhaps went into bad shape around 2021-12-15 when Ede fixed the cursor hotspot.
Alt-key has some effect, it activates the titles of the main menu and then the menus can be opened with the letter that is underlined in the title.

**Comment by edeso** [comment]
fixed with
https://github.com/openjump-gis/openjump/commit/d439096ef9460678d726690adbd2f0a0075a888f
&
https://github.com/openjump-gis/openjump/commit/29363fb76b095b07206b3554052cc569e65a577f
