### ISSUE TITLE
RunTime exception if I use zoom plugins from workbench statusbar

### ISSUE THREAD

**Issue by ma15569** [openjump-gis/openjump#58]
Clicking on lower bar, both on scale and on coordinate boxes should popup conresponding zoom plugins (Zoom to scale and Zoom to coordinate). 
With latest OJ Night Build ver 2.1,  I have RunTime exceptions.

java.lang.RuntimeException: Add super.initialize() to your AbstractPlugIn.initialize() implementation!
org.openjump.core.ui.plugin.view.ZoomToScalePlugIn

**Comment by edeso** [comment]
hey Peppe,

please try the next snapshot. the plugins needed to be initialized() before usage. just added it and initialized them lazily later.
