### ISSUE TITLE
dbf null number are written as 0

### ISSUE THREAD

**Issue by mukoki** [openjump-gis/openjump#64]
In Dbf, empty string in a number field is read as null, but then, null is written as 0 so that original dbf is not preserved after a read+write operation

**Comment by jratike80** [comment]
Probably this change is not harmful but I think that the old behavior was alike what ESRI does. See https://support.esri.com/en/technical-article/000005811.

> The attributes in a shapefile are maintained in a dBase file. Until dBase 7, the dBase format did not support the concept of a NULL value. In ArcView 3.x and in ArcMap 8.x, NULL integers in a shapefile are stored as 0, and NULL text strings are stored as a space.
