### ISSUE TITLE
I18N usage in extension

### ISSUE THREAD

**Issue by mukoki** [openjump-gis/openjump#8]
Could not find a way to use new I18N static getMessage methods in SkyJumpPrinter extension. For now, I still use the deprecated getText method.

**Comment by edeso** [comment]
this actually relates to https://sourceforge.net/p/jump-pilot/bugs/501/ and there is no reason to "fix" anything until I18N is overhauled as described.

Let me see if i find the time soonish to do so ;)

**Comment by mukoki** [comment]
Hi,I did not remember this discussion which is from last year only. My memory is getting shorter and shorter...I'm still OK with the proposed change. It's a good time to proceed ;-)Michaëlenvoyé : 7 avril 2021 à 12:30de : edeso ***@***.***>à : openjump-gis/openjump ***@***.***>cc : Michaël Michaud ***@***.***>, Author ***@***.***>objet : Re: [openjump-gis/openjump] I18N usage in extension (#8) this actually relates to https://sourceforge.net/p/jump-pilot/bugs/501/ and there is no reason to "fix" anything until I18N is overhauled as described.Let me see if i find the time soonish to do so ;)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by edeso** [comment]
good thing we have all those tagged TODOs on sf.net still then ;)

we should keep working on those until they are closed eventually.. ede

**Comment by edeso** [comment]
@mukoki can you please test and close if the issue is fixed properly on your side as well?

**Comment by mukoki** [comment]
Thanks for the effort, I'll have a look ASAP

**Comment by mukoki** [comment]
New I18N works fine for extensions !

**Comment by edeso** [comment]
good things come to pass :)
